# -*- coding: utf-8 -*-
"""Data visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i1QAWG-XCJ283nyNA5A7wv2lQxvsGBGQ
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

np.random.seed(0)

dates = pd.date_range(start='2019-01-01',periods = 5*12, freq='m')
sales_data = np.random.randint(10000, 50000, size=len(dates))

sales_df = pd.DataFrame({'Dates': dates, 'sales': sales_data})
sales_df

from matplotlib.projections.polar import PolarTransform
sns.set(style='whitegrid')
plt.figure(figsize=(14,10))

plt.subplot(2,2,1)
sns.lineplot(x='Dates', y='sales', data=sales_df)
plt.title('sales over time')
plt.xticks(rotation=45)
plt.gca().xaxis.set_major_locator(plt.MaxNLocator(5))

plt.subplot(2,2,2)
sales_df['Year'] = sales_df['Dates'].dt.year

sns.barplot(x='year', y='sales', data=sales_df, palette='viridis')
plt.title('Sales by Year')
plt.xticks(rotation=45)
plt.gca().xaxis.set_major_locator(plt.MaxNLocator(5))

plt.subplot(2,2,3)
Sales_by_year = sales_df.groupby('Year')['sales'].sum()
plt.pie(Sales_by_year, labels = Sales_by_year.index,autopct='%1.1f%%',startangle=140)
plt.axis('equal')
plt.title('Sales Distribution by Year')

plt.subplot(2,2,4)
sns.histplot(sales_df['sales'], bins=20,kde=True, color='skyblue')
plt.title('Sales Histogram')
plt.xlabel('Sales')
plt.ylabel('Frequency')

plt.tight_layout()
plt.show